spring.application.name=IMLID

# Server
server.port=8080

# Database (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/imlcore
spring.datasource.username=iml
spring.datasource.password=iml123

# MinIO


# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# JJWT
api.security.token.secret=

# Image
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB